# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrienchHouse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftHTTP'
  	pod 'SVProgressHUD'
	use_frameworks!
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'RxSwift'
  # Pods for FrienchHouse

end
